const NAME_SPACE = "COMMON";

export const CHANGE_SCHEMA = `${NAME_SPACE}/CHANGE_SCHEMA`;

export const ADD_PAGE_ITEM = `${NAME_SPACE}/ADD_ITEM`;

export const CHANGE_PAGE_ITEM = `${NAME_SPACE}/CHANGE_ITEM`;

export const DELETE_PAGE_ITEM = `${NAME_SPACE}/DELETE_ITEM`;

export const CHANGE_PAGE_ITEM_POSITION = `${NAME_SPACE}/CHANGE_POSITION`;

export const CHANGE_SCHEMA_ATTRIBUTES = `${NAME_SPACE}/CHANGE_SCHEMA_ATTRIBUTES`;
